exclude: >
  (?x)^(
      .*_pb2.py|
      .*_pb2_grpc.py
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: fix-byte-order-marker
      - id: check-docstring-first
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        args: ["--line-length", "120"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.9.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "120"]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ["--max-line-length", "120", "--ignore", "E203,W503"]
